### ISSUE TITLE
Chimera

### ISSUE THREAD

**Issue by Ibrahim77077** [Randy-420/Theos-Auto-Installer-u0-Checkra1n-odyssey#4]
What about Chimera? 
Does it work with it?
iOS 12.2 iPhone 9,1
Thank you

**Comment by Randy-420** [comment]
Shouldn't be an issue at all. I just haven't had any testers. If you need help or have any questions - please dm me on telegram: https://t.me/necr0sisOn Sat, Apr 30, 2022 at 5:59 PM Ibrahim77077 ***@***.***> wrote:
What about Chimera?
Does it work with it?
iOS 12.2 iPhone 9,1
Thank you

?Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
